services:
    db:
        image: postgres:16
        container_name: recife_postgres
        env_file:
            - .env
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

    etl:
        build: .
        container_name: recife_weather_etl
        depends_on:
            - db
        env_file:
            - .env
        command: ["python", "main.py"]

volumes:
    pgdata:
